version: "3"

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  api:
    image: node:18-alpine
    working_dir: /usr/src/app
    command: sh -c "npm i -g npm@9 && npm i && npm start"
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./:/usr/src/app
